CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    name          VARCHAR(150) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_role CHECK (role IN ('PATIENT', 'NUTRITIONIST'))
);

-- El email es único sin distinguir mayúsculas: "Ana@x.com" y "ana@x.com" son la misma cuenta
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));
